# Generated by Django 5.2.12 on 2026-04-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_subscriptionsystem_display_price_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TenantService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('service_type', models.CharField(choices=[('django_system', 'Django System'), ('wordpress_site', 'WordPress Site'), ('custom_site', 'Custom Site'), ('other', 'Other')], default='django_system', max_length=30)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('public_url', models.URLField(blank=True)),
                ('admin_url', models.URLField(blank=True)),
                ('license_key', models.CharField(max_length=64, unique=True)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('api_secret', models.CharField(max_length=64)),
                ('connection_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_service', to='catalog.subscription')),
                ('subscription_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_services', to='catalog.subscriptionsystem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.tenant')),
            ],
            options={
                'ordering': ['tenant__business_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantServiceAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_identifier', models.CharField(max_length=150)),
                ('role', models.CharField(default='admin', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='catalog.tenantservice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_admins', to='catalog.tenant')),
            ],
            options={
                'ordering': ['service__name', 'user_identifier'],
                'unique_together': {('service', 'user_identifier')},
            },
        ),
        migrations.CreateModel(
            name='TenantServiceFeatureAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_code', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access', to='catalog.tenantservice')),
            ],
            options={
                'ordering': ['service__name', 'feature_code'],
                'unique_together': {('service', 'feature_code')},
            },
        ),
    ]
