services:
  - type: web
    name: infaan-web
    runtime: node
    rootDir: infaan-next
    buildCommand: npm install && npm run build:prod
    startCommand: npm start
    healthCheckPath: /api/keepalive
    envVars:
      - key: NODE_VERSION
        value: 22.21.0
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_LIFETIME
        value: "7d"
      - key: JWT_REFRESH_LIFETIME
        value: "30d"
      - key: NEXT_PUBLIC_APP_URL
        value: https://infaan-web-design.onrender.com
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        value: 139448352472-lef1vd392sa52l7rm2tnplqj13iq1h7p.apps.googleusercontent.com
      - key: CORS_ALLOWED_ORIGINS
        value: "https://infaan-web-design.onrender.com,http://localhost:3000,http://127.0.0.1:3000"
      - key: SYSTEM_SUBSCRIPTION_API_URL
        value: "https://infaan-web-design.onrender.com/api"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_Bhgfp5GnV9XS@ep-fancy-block-atajo7jl-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
